In [1]:
import os
import sys
import tempfile
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

sys.path.insert(0, os.path.dirname(os.getcwd()))

# load the dataset
DATA_PATH = os.path.join(tempfile.gettempdir(), "retail_store_inventory.csv")

In [3]:
# DATA_PATH

In [4]:
df = pd.read_csv(DATA_PATH)

In [5]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [6]:
df = df.drop_duplicates()
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

In [7]:
df.shape

(73100, 15)

In [8]:
df['Date']

0       2022-01-01
1       2022-01-01
2       2022-01-01
3       2022-01-01
4       2022-01-01
           ...
73095   2024-01-01
73096   2024-01-01
73097   2024-01-01
73098   2024-01-01
73099   2024-01-01
Name: Date, Length: 73100, dtype: datetime64[us]

In [9]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['quarter'] = df['Date'].dt.quarter
df['day_of_week'] = df['Date'].dt.dayofweek # Monday=0, Sunday=6
df['is_weekend'] = (df['day_of_week'] >= 5).astype(int) # 1 for weekend, 0 for weekday
df['week_of_year'] = df['Date'].dt.isocalendar().week.astype(int) # Week number of the year (1-52)
df['days_since_start'] = (df['Date'] - df['Date'].min()).dt.days # Days since the earliest date in the dataset

print("Date features created successfully.")

Date features created successfully.

In [10]:
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Competitor Pricing,Seasonality,Year,Month,Day,quarter,day_of_week,is_weekend,week_of_year,days_since_start
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,...,29.69,Autumn,2022,1,1,1,5,1,52,0
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,66.16,Autumn,2022,1,1,1,5,1,52,0
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,...,31.32,Summer,2022,1,1,1,5,1,52,0
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,...,34.74,Autumn,2022,1,1,1,5,1,52,0
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,...,68.95,Summer,2022,1,1,1,5,1,52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,...,72.45,Winter,2024,1,1,1,0,0,1,730
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,...,83.78,Autumn,2024,1,1,1,0,0,1,730
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,...,10.91,Winter,2024,1,1,1,0,0,1,730
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,...,55.80,Spring,2024,1,1,1,0,0,1,730
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,...,79.52,Spring,2024,1,1,1,0,0,1,730